### ISSUE TITLE
Create goss docker project

### ISSUE THREAD

**Issue by EricCrosson** [EricCrosson/ansible-docker#5]
The goss docker-container should be specified in ansible, probably using the yeoman generator.

Because you have done the following more than three times:

```
job:
  image: hamroctopus/ansible:1.0.0
  stage: build
  before_script:
    - apt update
    - apt install -y curl
    - export GOSS_PATH=/usr/local/bin/goss
  script:
    - ./bin/apply
    - goss validate
```

it would be cleaner to write

```
job:
  image: hamroctopus/goss:1.0.0
  stage: build
  script:
    - ./bin/apply
    - goss validate
```
